import Link from "next/link";

import { BookingTrendChart, ClientMixChart, RevenueTrendChart } from "@/features/admin/components/admin-kpi-charts";
import { AdminPanel, AdminPageShell } from "@/features/admin/components/admin-page-shell";
import { KpiPeriodFilter } from "@/features/admin/components/kpi-period-filter";
import { KpiServicesTable } from "@/features/admin/components/kpi-services-table";
import { interpretKpiComparison } from "@/features/admin/lib/kpi-comparison";
import { kpiComparisonConfig } from "@/features/admin/lib/kpi-config";
import { type KpiDashboardData, type KpiMetric } from "@/features/admin/types/kpi-dashboard";

const money = new Intl.NumberFormat("cs-CZ", { style: "currency", currency: "CZK", maximumFractionDigits: 0 });
const number = new Intl.NumberFormat("cs-CZ", { maximumFractionDigits: 0 });
const percent = new Intl.NumberFormat("cs-CZ", { style: "percent", maximumFractionDigits: 1 });
const dateTime = new Intl.DateTimeFormat("cs-CZ", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/Prague" });

function metricDetail(metric: KpiMetric, formatter: (value: number) => string, lowerIsBetter = false, percentagePoints = false) {
  const comparison = interpretKpiComparison(metric, { lowerIsBetter });
  if (comparison.state === "unavailable") return "—";
  if (comparison.state === "new") return metric.value > 0 ? `Nově · +${percentagePoints ? `${number.format(metric.difference)} p. b.` : formatter(metric.difference)}` : "—";
  if (comparison.direction === "flat") return "Beze změny";
  const arrow = comparison.direction === "up" ? "↑" : comparison.direction === "down" ? "↓" : "→";
  const difference = percentagePoints ? `${metric.difference >= 0 ? "+" : ""}${number.format(metric.difference)} p. b.` : `${metric.difference >= 0 ? "+" : ""}${formatter(metric.difference)}`;
  return `${arrow} ${metric.change !== null ? `${metric.change >= 0 ? "+" : ""}${percent.format(metric.change / 100)} · ` : ""}${difference}`;
}
function InfoTooltip({ text }: { text: string }) {
  return <span className="group relative inline-flex align-middle">
    <button type="button" aria-label="Zobrazit definici metriky" className="inline-flex size-7 items-center justify-center rounded-full border border-white/12 text-xs normal-case tracking-normal text-white/60 transition hover:border-white/25 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-accent)]">i</button>
    <span role="tooltip" className="pointer-events-none absolute left-0 top-full z-20 mt-2 hidden w-64 rounded-xl border border-white/12 bg-neutral-950 p-3 text-left text-xs font-normal normal-case leading-5 tracking-normal text-white/80 shadow-xl group-hover:block group-focus-within:block">{text}</span>
  </span>;
}
function KpiCard({ label, metric, format, href, detail, tooltip, kpiKey, valueOverride }: { label: string; metric: KpiMetric; format: (value: number) => string; href?: string; detail?: string; tooltip?: string; kpiKey?: keyof typeof kpiComparisonConfig; valueOverride?: string }) {
  const config = kpiKey ? kpiComparisonConfig[kpiKey] : undefined;
  const body = <article className="rounded-[1.25rem] border border-white/10 bg-white/[0.045] p-4 transition hover:border-[var(--color-accent)]/40"><div className="flex min-h-7 items-start justify-between gap-2"><p className="pt-1 text-[10px] font-semibold uppercase tracking-[0.18em] text-white/52">{label}</p>{tooltip ? <InfoTooltip text={tooltip} /> : null}</div><p className="mt-1 font-display text-2xl text-white sm:text-3xl">{valueOverride ?? format(metric.value)}</p><p className="mt-2 text-xs text-white/60">{detail ?? metricDetail(metric, format, config?.lowerIsBetter, Boolean(config && "percentagePoints" in config && config.percentagePoints))}</p></article>;
  return href ? <Link href={href}>{body}</Link> : body;
}
export function AdminKpiDashboardPage({ data, area }: { data: KpiDashboardData; area: "owner" | "salon"; searchParams?: Record<string, string | string[] | undefined> }) {
  const path = area === "owner" ? "/admin/statistiky" : "/admin/provoz/statistiky";
  const bookingHref = area === "owner" ? "/admin/rezervace" : "/admin/provoz/rezervace";
  const unavailableComparisons = Object.values(data.metrics).filter((metric) => !metric.previousHasData).length;
  return <AdminPageShell eyebrow="Manažerský přehled" title="KPI a statistiky" description={`Výsledky za „${data.range.label}“ porovnáváme s bezprostředně předcházejícím stejně dlouhým obdobím. Přepočet: ${dateTime.format(data.calculatedAt)}.`} compact>
    <AdminPanel title="Období" description="Rychlá období se přepočítají ihned po kliknutí; vlastní rozsah potvrďte tlačítkem." compact denseHeader>
      <KpiPeriodFilter path={path} activePeriod={data.range.period} rangeLabel={formatRange(data.range.start, data.range.end)} initialFrom={formatInputDate(data.range.start)} initialTo={formatInputDate(new Date(data.range.end.getTime() - 1))} />
    </AdminPanel>
    {unavailableComparisons >= Math.ceil(Object.values(data.metrics).length / 2) ? <p className="rounded-xl border border-white/10 bg-white/[0.045] px-4 py-3 text-sm text-white/68">Porovnání není dostupné, protože pro předchozí období nemáme dostatek historických dat.</p> : null}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Tržby" metric={data.metrics.revenue} format={money.format} kpiKey="revenue" /><KpiCard label="Dokončené návštěvy" metric={data.metrics.completed} format={number.format} kpiKey="completed" /><KpiCard label="Průměrná útrata" metric={data.metrics.averageSpend} format={money.format} kpiKey="averageSpend" /><KpiCard label="Obsazenost" metric={data.metrics.occupancy} format={(v) => percent.format(v / 100)} kpiKey="occupancy" tooltip="Obsazenost vychází z aktuálně publikovaných slotů. Historické změny publikace ani opětovné uvolnění termínu model neukládá, proto může být u minulých období orientační." /><KpiCard label="Nové klientky" metric={data.metrics.newClients} format={number.format} kpiKey="newClients" /><KpiCard label="Vracející se klientky" metric={data.metrics.returningClients} format={number.format} kpiKey="returningClients" tooltip="Klientka s dokončenou návštěvou ve vybraném období a alespoň jednou dokončenou návštěvou před jeho začátkem." /><KpiCard label="Klientky s opakovanou návštěvou" metric={data.metrics.repeatVisitClients} format={number.format} kpiKey="repeatVisitClients" /><KpiCard label="Míra opakované návštěvy" metric={data.metrics.repeatVisitRate} format={(v) => percent.format(v / 100)} kpiKey="repeatVisitRate" /><KpiCard label="Storna" metric={data.metrics.cancellations} format={number.format} kpiKey="cancellations" detail={`${percent.format(data.metrics.cancellationRate.value / 100)} rezervací · Hodnota ${money.format(data.metrics.cancellationValue.value)} · ${metricDetail(data.metrics.cancellations, number.format, true)}`} /><KpiCard label="No-show" metric={data.metrics.noShows} format={number.format} kpiKey="noShows" detail={`${percent.format(data.metrics.noShowRate.value / 100)} rezervací · Hodnota ${money.format(data.metrics.noShowValue.value)} · ${metricDetail(data.metrics.noShows, number.format, true)}`} /><KpiCard label="Očekávané tržby" metric={data.metrics.expectedRevenue} format={money.format} kpiKey="expectedRevenue" valueOverride={data.expectedRevenue.isHistorical ? "—" : undefined} detail={data.expectedRevenue.isHistorical ? "Historické období" : `${number.format(data.expectedRevenue.bookingCount)} budoucích rezervací${data.expectedRevenue.missingPriceCount ? ` · ${number.format(data.expectedRevenue.missingPriceCount)} bez ceny` : ""}`} tooltip="Potvrzené budoucí rezervace ve vybraném období." /><KpiCard label="Neuhrazená částka" metric={data.metrics.outstanding} format={money.format} kpiKey="outstanding" href={`${bookingHref}?status=completed`} /></section>
    <section className="grid gap-4 xl:grid-cols-2"><AdminPanel title="Vývoj tržeb" description="Do 62 dní po dnech, delší období po měsících." compact denseHeader><RevenueTrendChart rows={data.revenueSeries} /></AdminPanel><AdminPanel title="Vývoj rezervací" description="Dokončené, zrušené a nedostavení se." compact denseHeader><BookingTrendChart rows={data.bookingSeries} /></AdminPanel></section>
    <section className="grid gap-4 xl:grid-cols-2"><AdminPanel title="Nejvýdělečnější služby" description="Historická cena a skutečně rezervovaný čas dokončených návštěv." compact denseHeader><div className="pt-4"><KpiServicesTable services={data.services} /></div></AdminPanel><AdminPanel title="Nové klientky a klientky s návštěvou před obdobím" description={`„Vracející se“ znamená dokončenou návštěvu ve vybraném období i alespoň jednu před jeho začátkem. Stav klientek k ${new Intl.DateTimeFormat("cs-CZ", { dateStyle: "medium", timeZone: "Europe/Prague" }).format(data.retentionReference)}.`} compact denseHeader><ClientMixChart newClients={data.clientMix.newClients} returningClients={data.clientMix.returningClients} /><div className="mt-5 space-y-2">{data.retention.map((item) => <Link key={item.band} href={item.href} className="flex items-center justify-between rounded-xl border border-white/10 px-3 py-3 text-sm hover:border-[var(--color-accent)]/40"><span>{item.label}</span><span className="font-display text-xl">{number.format(item.count)}</span></Link>)}</div></AdminPanel></section>
    <TablePanel title="Akviziční zdroje" description="Normalizovaný souhrn podle plánovaného data návštěvy. Hodnota rezervací je cena snapshotu všech rezervací, skutečné tržby jsou ceny dokončených návštěv a průměr je hodnota rezervací na jednu rezervaci." headers={["Zdroj", "Rezervace", "Dokončeno", "Hodnota rezervací", "Skutečné tržby", "Průměrná hodnota"]} empty="Pro vybrané období nejsou dostupná akviziční data." rows={data.acquisition.summary.map((row) => [row.source, number.format(row.bookings), number.format(row.completed), money.format(row.bookingValue), money.format(row.revenue), money.format(row.averageValue)])} />
    <TablePanel title="Detail akvizičních zdrojů" description="Rozpad podle zdroje, média a kampaně; hodnoty používají plánované datum návštěvy." headers={["Zdroj", "Médium", "Kampaň", "Rezervace", "Dokončeno", "Hodnota rezervací", "Skutečné tržby", "Průměrná hodnota"]} empty="Pro vybrané období nejsou dostupná akviziční data." rows={data.acquisition.detail.map((row) => [row.source, row.medium, row.campaign, number.format(row.bookings), number.format(row.completed), money.format(row.bookingValue), money.format(row.revenue), money.format(row.averageValue)])} />
  </AdminPageShell>;
}
function formatInputDate(value: Date) { return new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Prague", year: "numeric", month: "2-digit", day: "2-digit" }).format(value); }
function formatRange(start: Date, end: Date) { const formatter = new Intl.DateTimeFormat("cs-CZ", { day: "numeric", month: "numeric", year: "numeric", timeZone: "Europe/Prague" }); return `${formatter.format(start)}–${formatter.format(new Date(end.getTime() - 1))}`; }
function TablePanel({ title, description, headers, rows, empty }: { title: string; description?: string; headers: string[]; rows: string[][]; empty: string }) { return <AdminPanel title={title} description={description} compact denseHeader><div className="-mx-1 overflow-x-auto px-1 pb-1" tabIndex={0} aria-label={`${title}, tabulku lze posouvat vodorovně`}><table className="mt-4 min-w-[760px] text-left text-sm"><thead className="text-xs uppercase tracking-wider text-white/50"><tr>{headers.map((header) => <th key={header} scope="col" className="whitespace-nowrap px-3 py-2">{header}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, index) => <tr key={`${row[0]}-${index}`} className="border-t border-white/8 text-white/78">{row.map((cell, cellIndex) => cellIndex === 0 ? <th key={cellIndex} scope="row" className="whitespace-nowrap px-3 py-3 font-medium text-white">{cell}</th> : <td key={cellIndex} className="whitespace-nowrap px-3 py-3">{cell}</td>)}</tr>) : <tr><td colSpan={headers.length} className="px-3 py-10 text-white/60">{empty}</td></tr>}</tbody></table></div></AdminPanel>; }
export function AdminKpiDashboardSkeleton() { return <div className="space-y-4 animate-pulse"><div className="h-32 rounded-[var(--radius-panel)] bg-white/8" /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 8 }, (_, index) => <div key={index} className="h-32 rounded-[1.25rem] bg-white/6" />)}</div></div>; }
