"use client";

import FullCalendar from "@fullcalendar/react";
import csLocale from "@fullcalendar/react/locales/cs";
import interactionPlugin from "@fullcalendar/react/interaction";
import themePlugin from "@fullcalendar/react/themes/classic";
import timeGridPlugin from "@fullcalendar/react/timegrid";
import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { CalendarApi, DateClickInfo, DateSelectInfo, DatesSetInfo, EventClickInfo } from "@fullcalendar/react";

import { applyPlannerSelectionAction } from "@/features/admin/actions/slot-planner-actions";
import type { PlannerDay, PlannerWeekData } from "@/features/admin/lib/admin-slots";
import { addDays, dateToCellIndex, formatDateKey, getDayBounds } from "@/features/admin/lib/admin-slots/time";
import { buildIntervalsFromCells, cloneWeekDays, hasBlockedCells, patchDayAvailableIntervals } from "./admin-weekly-planner-helpers";
import { plannerWeekToFullCalendarEvents, type PlannerLabEventType } from "./planner-lab-adapter";
import { getPlannerLabDefaultView, getPlannerLabWeekStart, isPlannerLabMobileViewport, movePlannerLabWeek, type PlannerLabView } from "./planner-lab-week";
import { PlannerLabSaveQueue } from "./planner-lab-save-queue";
import styles from "./planner-lab.module.css";

type PlannerMode = "view" | "add" | "remove";
type PlannerChange = { days: PlannerDay[]; dateKey: string; startCell: number; endCell: number; mode: Exclude<PlannerMode, "view">; revertedOperationId?: string };
type UndoChange = Omit<PlannerChange, "days">;

function formatWeekRange(weekStart: string) { const start = getDayBounds(weekStart).startsAt; const end = addDays(start, 6); const dayMonth = new Intl.DateTimeFormat("cs-CZ", { day: "numeric", month: "long", timeZone: "Europe/Prague" }); const year = new Intl.DateTimeFormat("cs-CZ", { year: "numeric", timeZone: "Europe/Prague" }); return `${dayMonth.format(start)} – ${dayMonth.format(end)} ${year.format(end)}`; }
function modeLabel(mode: PlannerMode) { return mode === "add" ? "Přidat termín" : mode === "remove" ? "Odebrat termín" : "Prohlížení"; }
function getPlannerBookingHref(area: PlannerWeekData["area"], bookingId: string) { return area === "owner" ? `/admin/rezervace/${bookingId}` : `/admin/provoz/rezervace/${bookingId}`; }

export function AdminWeeklyPlannerClient({ data, weekStart, initialDate, hasInitialDay = false, routeBase }: { data: PlannerWeekData; weekStart: string; initialDate?: string; hasInitialDay?: boolean; routeBase: string }) {
  const router = useRouter();
  const calendarRef = useRef<{ getApi: () => CalendarApi } | null>(null);
  const calendarContainerRef = useRef<HTMLDivElement>(null);
  const scrollPositionRef = useRef<{ pageX: number; pageY: number; calendarY: number } | null>(null);
  const effectiveInitialDate = initialDate ?? weekStart;
  const requestedWeekRef = useRef(weekStart); const requestedDateRef = useRef(effectiveInitialDate);
  const recentCellMutationRef = useRef<{ dateKey: string; startCell: number; endCell: number; expiresAt: number } | null>(null);
  const datesSetFrameRef = useRef<number | null>(null); const hydratedWeekRef = useRef(weekStart); const restoreRequestedRef = useRef(false);
  const contextRef = useRef({ area: data.area, weekKey: data.weekKey }); const confirmedDaysRef = useRef(cloneWeekDays(data.days));
  const saveQueueRef = useRef<PlannerLabSaveQueue<PlannerChange> | null>(null);
  const [mounted, setMounted] = useState(false); const [compact, setCompact] = useState(false);
  const [days, setDays] = useState<PlannerDay[]>(() => cloneWeekDays(data.days));
  const [message, setMessage] = useState<string | null>("Prohlížení – kalendář nic nemění."); const [saveError, setSaveError] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false); const [isWeekLoading, setIsWeekLoading] = useState(false);
  const [openWeekStart, setOpenWeekStart] = useState(weekStart); const [activeView, setActiveView] = useState<PlannerLabView>("timeGridWorkWeek");
  const [mode, setMode] = useState<PlannerMode>("view");
  const [undoChange, setUndoChange] = useState<UndoChange | null>(null); const undoTimeoutRef = useRef<number | null>(null);
  function clearUndo() { if (undoTimeoutRef.current !== null) window.clearTimeout(undoTimeoutRef.current); undoTimeoutRef.current = null; setUndoChange(null); }
  function offerUndo(change: PlannerChange, operationId?: string) { clearUndo(); setUndoChange({ dateKey: change.dateKey, startCell: change.startCell, endCell: change.endCell, mode: change.mode, revertedOperationId: operationId }); undoTimeoutRef.current = window.setTimeout(() => setUndoChange(null), 12_000); }
  useEffect(() => () => { if (undoTimeoutRef.current !== null) window.clearTimeout(undoTimeoutRef.current); }, []);
  useEffect(() => { saveQueueRef.current = new PlannerLabSaveQueue(
    async (change) => { const context = contextRef.current; const result = await applyPlannerSelectionAction(context.area, { weekKey: context.weekKey, dateKey: change.dateKey, startCell: change.startCell, endCell: change.endCell, mode: change.mode, revertedOperationId: change.revertedOperationId }); return result.ok ? { ok: true as const, operationId: result.operationId } : { ok: false as const, message: result.message }; },
    setIsSaving,
    (savedChange, result) => { confirmedDaysRef.current = cloneWeekDays(savedChange.days); offerUndo(savedChange, result.operationId); },
    () => { setSaveError(null); setMessage("Uloženo"); },
    (error) => { setSaveError(error); setMessage(error); },
  ); return () => { saveQueueRef.current = null; }; }, []);
  useEffect(() => { const media = window.matchMedia("(max-width: 1023px)"); const update = () => setCompact(isPlannerLabMobileViewport(window.innerWidth)); const frame = window.requestAnimationFrame(() => { update(); setMounted(true); }); media.addEventListener("change", update); return () => { window.cancelAnimationFrame(frame); media.removeEventListener("change", update); }; }, []);
  useEffect(() => () => { if (datesSetFrameRef.current !== null) window.cancelAnimationFrame(datesSetFrameRef.current); }, []);
  useEffect(() => { if (data.weekKey !== requestedWeekRef.current || (data.weekKey === hydratedWeekRef.current && !restoreRequestedRef.current)) return; restoreRequestedRef.current = false; hydratedWeekRef.current = data.weekKey; contextRef.current = { area: data.area, weekKey: data.weekKey }; const nextDays = cloneWeekDays(data.days); confirmedDaysRef.current = nextDays; setDays(cloneWeekDays(nextDays)); setOpenWeekStart(data.weekKey); setSaveError(null); setIsWeekLoading(false); calendarRef.current?.getApi().gotoDate(requestedDateRef.current); }, [data]);
  useEffect(() => { if (!mounted) return; const nextView = getPlannerLabDefaultView(compact); const frame = window.requestAnimationFrame(() => { setActiveView(nextView); const calendar = calendarRef.current?.getApi(); const mobileToday = !hasInitialDay && data.days.some((day) => day.dateKey === data.todayKey) ? data.todayKey : requestedDateRef.current; const targetDate = compact ? mobileToday : requestedDateRef.current; if (compact && !hasInitialDay) requestedDateRef.current = mobileToday; calendar?.changeView(nextView, targetDate); }); return () => window.cancelAnimationFrame(frame); }, [compact, data.days, data.todayKey, hasInitialDay, mounted]);

  const events = useMemo(() => plannerWeekToFullCalendarEvents(data, days), [data, days]);
  const canEdit = !isWeekLoading && !saveError; const canNavigate = !isSaving && !isWeekLoading;
  function getCalendarScroller() { return [...(calendarContainerRef.current?.querySelectorAll<HTMLElement>("*") ?? [])].find((element) => { const overflowY = window.getComputedStyle(element).overflowY; return (overflowY === "auto" || overflowY === "scroll") && element.scrollHeight > element.clientHeight; }); }
  function rememberScrollPosition() { if (!compact) return; const scroller = getCalendarScroller(); scrollPositionRef.current = { pageX: window.scrollX, pageY: window.scrollY, calendarY: scroller?.scrollTop ?? 0 }; }
  function restoreScrollPosition() { const position = scrollPositionRef.current; if (!position) return; window.requestAnimationFrame(() => window.requestAnimationFrame(() => { const scroller = getCalendarScroller(); window.scrollTo({ left: position.pageX, top: position.pageY, behavior: "auto" }); if (scroller) scroller.scrollTop = position.calendarY; scrollPositionRef.current = null; })); }
  function selectAllow(info: { start: Date; end: Date }) { if (!canEdit || mode === "view") return false; const day = days.find((item) => item.dateKey === formatDateKey(info.start)); if (!day) return false; const startCell = dateToCellIndex(info.start); const endCell = dateToCellIndex(info.end); return endCell > startCell && !hasBlockedCells(day, startCell, endCell); }
  function saveAvailabilityChange(nextDays: PlannerDay[], dateKey: string, startCell: number, endCell: number, nextMode: Exclude<PlannerMode, "view">, revertedOperationId?: string) { setDays(nextDays); restoreScrollPosition(); setMessage("Ukládám…"); clearUndo(); saveQueueRef.current?.enqueue({ days: cloneWeekDays(nextDays), dateKey, startCell, endCell, mode: nextMode, revertedOperationId }); }
  function retrySave() { setSaveError(null); setMessage("Ukládám…"); saveQueueRef.current?.retry(); }
  function restoreSavedState() { saveQueueRef.current?.discardPending(); setDays(cloneWeekDays(confirmedDaysRef.current)); setSaveError(null); setMessage("Uloženo"); restoreRequestedRef.current = true; router.refresh(); }
  function updateAvailabilityRange(dateKey: string, startCell: number, endCell: number, nextMode: Exclude<PlannerMode, "view">, shouldRememberScroll = true, revertedOperationId?: string) {
    if (!canEdit) return; const recent = recentCellMutationRef.current;
    if (recent && recent.dateKey === dateKey && recent.startCell === startCell && recent.endCell === endCell && recent.expiresAt > Date.now()) return;
    const day = days.find((item) => item.dateKey === dateKey);
    if (!day || endCell <= startCell || startCell < 0 || endCell > 28 || hasBlockedCells(day, startCell, endCell)) { setMessage("Rezervace, úklid a chráněné intervaly nelze upravit."); return; }
    if (nextMode === "remove" && !day.cells.available.slice(startCell, endCell).some(Boolean)) { setMessage("V označeném čase není dostupnost k odebrání."); return; }
    recentCellMutationRef.current = { dateKey, startCell, endCell, expiresAt: Date.now() + 400 }; if (shouldRememberScroll) rememberScrollPosition();
    const cells = [...day.cells.available]; for (let cell = startCell; cell < endCell; cell += 1) cells[cell] = nextMode === "add";
    const nextDays = days.map((item) => item.dateKey === dateKey ? patchDayAvailableIntervals(item, buildIntervalsFromCells(cells)) : item); saveAvailabilityChange(nextDays, dateKey, startCell, endCell, nextMode, revertedOperationId);
  }
  function handleSelect(info: DateSelectInfo) { const dateKey = formatDateKey(info.start); const startCell = dateToCellIndex(info.start); const endCell = dateToCellIndex(info.end); rememberScrollPosition(); info.view.calendar.unselect(); if (mode !== "view") updateAvailabilityRange(dateKey, startCell, endCell, mode, false); }
  function handleDateClick(info: DateClickInfo) { if (mode === "view") return; const dateKey = formatDateKey(info.date); const cell = dateToCellIndex(info.date); updateAvailabilityRange(dateKey, cell, cell + 1, mode); }
  function handleEventClick(info: EventClickInfo) { const details = info.event.extendedProps as { type: PlannerLabEventType; bookingId?: string }; if ((details.type === "booking" || details.type === "completed") && details.bookingId) router.push(getPlannerBookingHref(data.area, details.bookingId)); }
  function undoLastChange() { if (!undoChange || isSaving || isWeekLoading) return; const reverseMode = undoChange.mode === "add" ? "remove" : "add"; const revertedOperationId = undoChange.revertedOperationId; clearUndo(); updateAvailabilityRange(undoChange.dateKey, undoChange.startCell, undoChange.endCell, reverseMode, true, revertedOperationId); }
  function requestWeek(nextWeekStart: string, focusDate = nextWeekStart) { if (!canNavigate) return; requestedDateRef.current = focusDate; if (nextWeekStart === requestedWeekRef.current) { calendarRef.current?.getApi().gotoDate(focusDate); router.replace(`${routeBase}?week=${nextWeekStart}&day=${focusDate}`, { scroll: false }); return; } requestedWeekRef.current = nextWeekStart; setIsWeekLoading(true); setOpenWeekStart(nextWeekStart); calendarRef.current?.getApi().gotoDate(focusDate); router.replace(`${routeBase}?week=${nextWeekStart}&day=${focusDate}`, { scroll: false }); }
  function handleDatesSet(info: DatesSetInfo) { if (datesSetFrameRef.current !== null) window.cancelAnimationFrame(datesSetFrameRef.current); datesSetFrameRef.current = window.requestAnimationFrame(() => { datesSetFrameRef.current = null; const currentDate = calendarRef.current?.getApi().getDate() ?? info.view.currentStart; const nextWeekStart = getPlannerLabWeekStart(currentDate); const focusDate = formatDateKey(currentDate); setOpenWeekStart(nextWeekStart); if (nextWeekStart !== requestedWeekRef.current && canNavigate) { requestWeek(nextWeekStart, focusDate); return; } if (focusDate !== requestedDateRef.current) { requestedDateRef.current = focusDate; router.replace(`${routeBase}?week=${nextWeekStart}&day=${focusDate}`, { scroll: false }); } }); }
  function changeView(view: PlannerLabView) { if (!canNavigate) return; setActiveView(view); const date = view === "timeGridWeekend" ? formatDateKey(addDays(getDayBounds(openWeekStart).startsAt, 5)) : view === "timeGridDay" ? requestedDateRef.current : openWeekStart; calendarRef.current?.getApi().changeView(view, date); }
  function moveNavigation(amount: -1 | 1) { const calendar = calendarRef.current?.getApi(); if (activeView === "timeGridDay") { const currentDate = formatDateKey(calendar?.getDate() ?? getDayBounds(requestedDateRef.current).startsAt); const nextDate = formatDateKey(addDays(getDayBounds(currentDate).startsAt, amount)); requestWeek(getPlannerLabWeekStart(getDayBounds(nextDate).startsAt), nextDate); return; } const nextWeekStart = movePlannerLabWeek(openWeekStart, amount); const focusDate = activeView === "timeGridWeekend" ? formatDateKey(addDays(getDayBounds(nextWeekStart).startsAt, 5)) : nextWeekStart; requestWeek(nextWeekStart, focusDate); }
  const initialView = getPlannerLabDefaultView(compact); const status = isWeekLoading ? "Načítám týden…" : isSaving ? "Ukládám…" : saveError ?? message;
  const viewChoices = compact ? ([['timeGridDay', 'Den'], ['timeGridWorkWeek', 'Po–Pá'], ['timeGridWeekend', 'Víkend']] as const) : ([['timeGridWorkWeek', 'Po–Pá'], ['timeGridWeek', 'Celý týden']] as const);
  return <div className={styles.planner}>
    <div className={styles.controls}><span className={styles.weekRange}>{formatWeekRange(openWeekStart)}</span><div className={styles.navigation} aria-label="Navigace týdne"><button type="button" className={styles.controlButton} onClick={() => moveNavigation(-1)} aria-label={activeView === "timeGridDay" ? "Předchozí den" : "Předchozí týden"} disabled={!canNavigate}>←</button><button type="button" className={styles.controlButton} onClick={() => { const today = formatDateKey(new Date()); requestWeek(getPlannerLabWeekStart(new Date()), today); }} disabled={!canNavigate}>Dnes</button><button type="button" className={styles.controlButton} onClick={() => moveNavigation(1)} aria-label={activeView === "timeGridDay" ? "Následující den" : "Následující týden"} disabled={!canNavigate}>→</button></div><div className={styles.viewSwitch} aria-label="Pohled kalendáře">{viewChoices.map(([view, label]) => <button key={view} type="button" className={`${styles.viewButton} ${activeView === view ? styles.viewButtonActive : ""}`} onClick={() => changeView(view)} disabled={!canNavigate} aria-pressed={activeView === view}>{label}</button>)}</div><div className={styles.modeSwitch} aria-label="Režim úprav">{(["view", "add", "remove"] as const).map((item) => <button key={item} type="button" className={`${styles.modeButton} ${mode === item ? styles.modeButtonActive : ""}`} onClick={() => { setMode(item); setMessage(item === "view" ? "Prohlížení – kalendář nic nemění." : `${modeLabel(item)} – zvolený interval se uloží.`); }} disabled={!canEdit} aria-pressed={mode === item}>{modeLabel(item)}</button>)}</div><div className={styles.status} role="status" aria-live="polite"><span>{status}</span></div>{saveError ? <div className={styles.statusActions}><button type="button" onClick={retrySave} className={styles.retryButton}>Zkusit znovu</button><button type="button" onClick={restoreSavedState} className={styles.retryButton}>Obnovit uložený stav</button></div> : null}{undoChange ? <button type="button" onClick={undoLastChange} className={styles.retryButton}>Vrátit změnu</button> : null}</div>
    <div className={styles.legend} aria-label="Legenda kalendáře"><span><i className={styles.legendAvailability} aria-hidden="true" />Volný termín</span><span><i className={styles.legendBooking} aria-hidden="true" />Rezervace</span><span><i className={styles.legendCleanup} aria-hidden="true" />Úklid</span><span><i className={styles.legendProtected} aria-hidden="true" />Chráněný interval</span><span><i className={styles.legendUnsaved} aria-hidden="true" />Neuložený stav</span><span><i className={styles.legendError} aria-hidden="true" />Chyba ukládání</span></div>
    <div ref={calendarContainerRef} className={`${styles.calendar} ${activeView === "timeGridWorkWeek" ? styles.workWeek : ""}`} data-testid="fullcalendar-planner">{mounted ? <FullCalendar key={compact ? "compact" : "desktop"} ref={calendarRef} plugins={[themePlugin, timeGridPlugin, interactionPlugin]} locales={[csLocale]} locale="cs" colorScheme="dark" initialView={initialView} initialDate={effectiveInitialDate} firstDay={1} timeZone="Europe/Prague" events={events} selectable={canEdit && mode !== "view"} selectMirror={compact} longPressDelay={compact ? 450 : undefined} selectLongPressDelay={compact ? 450 : undefined} selectAllow={selectAllow} select={handleSelect} dateClick={handleDateClick} eventClick={handleEventClick} eventDidMount={(info) => { const details = info.event.extendedProps as { type: PlannerLabEventType; clientName?: string; serviceName?: string }; const label = details.type === "booking" || details.type === "completed" ? `${details.type === "completed" ? "Dokončená rezervace" : "Rezervace"}: ${details.serviceName ?? "služba"}, ${details.clientName ?? "klientka"}. Otevřít detail.` : info.event.title; info.el.setAttribute("aria-label", label); if (details.type === "booking" || details.type === "completed") info.el.setAttribute("title", label); }} datesSet={handleDatesSet} editable={false} eventStartEditable={false} eventDurationEditable={false} allDaySlot={false} slotMinTime="06:00:00" slotMaxTime="20:00:00" slotDuration="00:30:00" snapDuration="00:30:00" scrollTimeReset={false} height="100%" expandRows nowIndicator weekends slotEventOverlap={false} eventMinHeight={0} eventShortHeight={0} views={{ timeGridWorkWeek: { type: "timeGrid", duration: { days: 5 } }, timeGridWeekend: { type: "timeGrid", duration: { days: 2 } }}} eventContent={(arg) => { const details = arg.event.extendedProps as { type: PlannerLabEventType; clientName?: string; serviceName?: string }; if (details.type === "availability" || details.type === "protected") return null; if (details.type === "cleanup") return <span className={styles.cleanupEvent}><b>{arg.timeText}</b><span>Úklid</span></span>; const eventLabel = details.clientName || arg.event.title || (details.type === "booking" ? "Rezervace" : "Dokončeno"); return <span className={styles.eventShort}><b>{arg.timeText}</b><span>{eventLabel}</span></span>; }} /> : <div className="h-full animate-pulse bg-white/[.04]" />}</div>
  </div>;
}
