"use client";

import { type ColumnDef, flexRender, getCoreRowModel, useReactTable } from "@tanstack/react-table";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useRef, useState } from "react";
import { type AdminArea } from "@/config/navigation";
import { type ReservationsDashboardData } from "@/features/admin/lib/admin-data";
import { cn } from "@/lib/utils";
import { AdminBookingsQuickActions } from "./admin-bookings-quick-actions";

type Booking = ReservationsDashboardData["sections"][number]["items"][number];
export function AdminBookingsWorkspace({ area, data }: { area: AdminArea; data: ReservationsDashboardData }) {
  const router = useRouter(); const [toast, setToast] = useState<string | null>(null); const refs = useRef<Array<HTMLTableRowElement | null>>([]);
  const rows = data.sections.flatMap((section) => section.items);
  const columns = useMemo(() => createBookingColumns(area, setToast), [area]);
  // TanStack Table returns mutable table helpers; these remain local to this non-memoized component.
  // eslint-disable-next-line react-hooks/incompatible-library
  const table = useReactTable({ data: rows, columns, getCoreRowModel: getCoreRowModel(), getRowId: (booking) => booking.id });
  const indexById = new Map(rows.map((row, index) => [row.id, index]));
  useEffect(() => { if (!toast) return; const id = window.setTimeout(() => setToast(null), 2600); return () => window.clearTimeout(id); }, [toast]);
  const open = (booking: Booking, index: number, event: React.KeyboardEvent<HTMLTableRowElement>) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); router.push(booking.href); } if (event.key === "ArrowDown" || event.key === "ArrowUp") { event.preventDefault(); refs.current[Math.max(0, Math.min(rows.length - 1, index + (event.key === "ArrowDown" ? 1 : -1)))]?.focus(); } };
  return <div className="space-y-3"><div className="hidden overflow-x-auto rounded-[1.35rem] border border-white/10 bg-white/[.03] md:block"><table className="min-w-[860px] w-full border-collapse"><thead className="sticky top-0 z-10 bg-[#151219]"><tr>{table.getHeaderGroups()[0]?.headers.map((header) => <th key={header.id} className="px-4 py-3 text-left text-[10px] font-semibold uppercase tracking-[.18em] text-white/42">{header.isPlaceholder ? null : flexRender(header.column.columnDef.header, header.getContext())}</th>)}</tr></thead>{data.sections.map((section) => <tbody key={section.key} className="border-t border-white/8"><tr><th colSpan={columns.length} className="bg-white/[.035] px-4 py-2 text-left text-xs font-semibold text-[var(--color-accent-soft)]">{section.label}{section.detail ? <span className="ml-2 font-normal text-white/45">{section.detail}</span> : null}</th></tr>{section.items.map((booking) => { const row = table.getRowModel().rowsById[booking.id]; const index = indexById.get(booking.id) ?? 0; return <tr key={booking.id} ref={(node) => { refs.current[index] = node; }} tabIndex={0} onClick={() => router.push(booking.href)} onKeyDown={(event) => open(booking,index,event)} className={cn("cursor-pointer border-t border-white/8 outline-none transition hover:bg-white/[.035] focus-visible:ring-2 focus-visible:ring-[var(--color-accent)]/50", booking.needsClosure ? "bg-orange-400/[.055]" : booking.isPending ? "bg-amber-400/[.045]" : booking.isMuted && "opacity-65")}>{row?.getVisibleCells().map((cell) => <td key={cell.id} className="px-4 py-3 align-middle text-sm">{flexRender(cell.column.columnDef.cell, cell.getContext())}</td>)}</tr>; })}</tbody>)}</table></div><div className="space-y-3 md:hidden">{data.sections.map((section) => <section key={section.key}><h2 className="px-1 py-2 text-xs font-semibold text-[var(--color-accent-soft)]">{section.label}</h2><div className="space-y-2">{section.items.map((booking) => <MobileCard key={booking.id} booking={booking} area={area} onSuccess={setToast}/>)}</div></section>)}</div>{data.summary.showMoreHref ? <div className="flex justify-center"><Link href={data.summary.showMoreHref} scroll={false} className="min-h-10 rounded-full border border-[var(--color-accent)]/36 px-4 py-2 text-sm font-semibold">Zobrazit další</Link></div> : null}{toast ? <div role="status" className="fixed bottom-4 right-4 rounded-xl border border-emerald-300/20 bg-[#17141b] px-4 py-3 text-sm text-white">{toast}</div> : null}</div>;
}
function createBookingColumns(area: AdminArea, onSuccess: (message:string)=>void): ColumnDef<Booking>[] { return [{ accessorKey:"scheduledTimeLabel", header:"Termín", cell:({row})=><strong className="whitespace-nowrap text-white">{row.original.scheduledTimeLabel}</strong> },{ accessorKey:"title", header:"Klientka / služba", cell:({row})=><div><Link href={row.original.href} onClick={(event)=>event.stopPropagation()} className="font-medium text-white hover:underline">{row.original.title}</Link><p className="mt-0.5 text-xs text-white/55">{row.original.serviceName}</p></div> },{ accessorKey:"statusLabel", header:"Stav", cell:({row})=><StatusBadge booking={row.original}/> },{ accessorKey:"primaryContactLabel", header:"Kontakt", cell:({row})=>row.original.primaryContactHref ? <a href={row.original.primaryContactHref} onClick={(event)=>event.stopPropagation()} className="text-white/80 hover:text-white">{row.original.primaryContactLabel}</a> : <span className="text-white/42">bez kontaktu</span> },{ id:"actions", header:"Akce", cell:({row})=><div onClick={(event)=>event.stopPropagation()}><AdminBookingsQuickActions area={area} bookingId={row.original.id} href={row.original.href} status={row.original.status} availableActions={row.original.availableActions} onSuccess={onSuccess}/></div> }]; }
function MobileCard({booking,area,onSuccess}:{booking:Booking;area:AdminArea;onSuccess:(message:string)=>void}) { return <article className={cn("rounded-xl border border-white/10 px-3 py-3",booking.needsClosure?"bg-orange-400/[.06]":booking.isPending?"bg-amber-400/[.05]":booking.isMuted&&"opacity-65")}><div className="flex items-start justify-between gap-2"><strong className="text-lg text-white">{booking.scheduledTimeLabel}</strong><StatusBadge booking={booking}/></div><Link href={booking.href} className="mt-2 block font-medium text-white">{booking.title}</Link><p className="text-sm text-white/60">{booking.serviceName}</p><p className="mt-2 text-sm text-white/75">{booking.primaryContactLabel ?? "bez kontaktu"}</p><div className="mt-3"><AdminBookingsQuickActions area={area} bookingId={booking.id} href={booking.href} status={booking.status} availableActions={booking.availableActions} onSuccess={onSuccess}/></div></article>; }
function StatusBadge({booking}:{booking:Booking}) { return <span className={cn("inline-flex rounded-full border px-2.5 py-1 text-[11px] font-semibold",booking.needsClosure?"border-orange-300/45 bg-orange-400/15 text-orange-100":booking.isPending?"border-amber-300/45 bg-amber-400/15 text-amber-50":booking.isMuted?"border-white/10 text-white/55":"border-sky-300/30 bg-sky-400/10 text-sky-100")}>{booking.statusLabel}</span>; }
