import Link from 'next/link';
import { MediaCollectionType } from '@/generated/prisma/browser';
import { type AdminArea } from '@/config/navigation';
import { uploadMediaAction } from '@/features/admin/actions/media-actions';
import { AdminPageShell, AdminPanel } from '@/features/admin/components/admin-page-shell';
import { MediaUploadDropzone } from '@/features/admin/components/media-upload-dropzone';
import { MediaAssetDetailDialog } from '@/features/admin/components/media-asset-detail-dialog';
import { ReferenceMediaSection, type ReferenceMediaItem } from '@/features/admin/components/reference-media-section';
import { getMediaAdminPath } from '@/features/admin/lib/admin-media-validation';
import { getMediaAssetUsage } from '@/features/media/lib/media-asset-usage';
import { listMedia } from '@/features/media/lib/media-library';
import { prisma } from '@/lib/prisma';

type Asset = Awaited<ReturnType<typeof listMedia>>[number];
type Membership = { type: MediaCollectionType; sortOrder: number; isVisible: boolean };
const collections = [{ type: MediaCollectionType.STUDIO_GALLERY, label: 'Studio' }, { type: MediaCollectionType.CERTIFICATES, label: 'Certifikáty' }, { type: MediaCollectionType.REFERENCES, label: 'Reference' }] as const;
function flashMessage(flash?: string) { return ({ 'media-upload-success': 'Médium bylo nahrané.', 'media-replace-success': 'Soubor byl bezpečně nahrazen při zachování vazeb.', 'media-delete-success': 'Médium bylo odstraněné.', 'media-delete-in-use': 'Toto médium nelze smazat, protože je stále používané. Nejprve odeberte uvedené vazby.', 'media-membership-success': 'Členství v kolekci bylo uložené.', 'media-update-success': 'Metadata média byla uložená.', 'media-upload-missing-file': 'Vyberte prosím obrázek.', 'media-upload-empty-file': 'Vybraný soubor je prázdný.', 'media-upload-invalid-type': 'Použijte JPG, PNG nebo WebP.', 'media-upload-too-large': 'Soubor je příliš velký. Limit je 8 MB.', 'media-upload-failed': 'Médium se nepodařilo zpracovat. Zkuste to prosím znovu.', 'media-replace-invalid-payload': 'Soubor se nepodařilo nahradit. Vyberte prosím platný obrázek.' } as Record<string, string>)[flash ?? '']; }

export async function AdminMediaPage({ area, searchParams }: { area: AdminArea; searchParams?: Record<string, string | string[] | undefined> }) {
  const raw = (name: string) => typeof searchParams?.[name] === 'string' ? searchParams[name] as string : undefined;
  const search = raw('q')?.trim().toLocaleLowerCase('cs-CZ') ?? '';
  const usageFilter = raw('usage') === 'USED' || raw('usage') === 'UNUSED' ? raw('usage') : 'ALL';
  const category = collections.some(({ type }) => type === raw('collection')) ? raw('collection') as MediaCollectionType : undefined;
  const [assets, rows, referenceRows] = await Promise.all([listMedia(), prisma.mediaCollectionItem.findMany({ select: { mediaAssetId: true, sortOrder: true, isVisible: true, collection: { select: { type: true } } } }), prisma.mediaCollectionItem.findMany({ where: { collection: { type: MediaCollectionType.REFERENCES } }, orderBy: [{ sortOrder: 'asc' }, { id: 'asc' }], select: { id: true, mediaAssetId: true, sortOrder: true, isVisible: true, altText: true, caption: true } })]);
  const referenceItems = referenceRows.map((item): ReferenceMediaItem | null => {
    const asset = assets.find((candidate) => candidate.id === item.mediaAssetId);
    return asset ? { ...item, mediaAsset: { id: asset.id, title: asset.title, fileName: asset.fileName, altText: asset.altText, thumbnailPublicUrl: asset.thumbnailPublicUrl, publicUrl: asset.publicUrl } } : null;
  }).filter((item): item is ReferenceMediaItem => item !== null);
  const memberships = new Map<string, Membership[]>();
  rows.forEach((row) => memberships.set(row.mediaAssetId, [...(memberships.get(row.mediaAssetId) ?? []), { type: row.collection.type, sortOrder: row.sortOrder, isVisible: row.isVisible }]));
  const usages = new Map(await Promise.all(assets.map(async (asset) => [asset.id, await getMediaAssetUsage(asset.id)] as const)));
  const filtered = assets.filter((asset) => { const usage = usages.get(asset.id)!; return (!search || [asset.title, asset.fileName, asset.originalFilename, asset.altText].some((value) => value?.toLocaleLowerCase('cs-CZ').includes(search))) && (usageFilter === 'ALL' || usage.isUsed === (usageFilter === 'USED')) && (!category || memberships.get(asset.id)?.some((item) => item.type === category)); });
  const base = getMediaAdminPath(area);
  const href = (next: Record<string, string | undefined>) => { const query = new URLSearchParams(); Object.entries({ q: search || undefined, usage: usageFilter === 'ALL' ? undefined : usageFilter, collection: category, ...next }).forEach(([key, value]) => value && query.set(key, value)); return `${base}${query.size ? `?${query}` : ''}`; };
  return <AdminPageShell eyebrow="Obsah webu" title="Média" description="Centrální knihovna souborů a jejich skutečných použití." stats={[{ label: 'Assetů', value: String(assets.length), tone: 'default' }, { label: 'Použitých', value: String([...usages.values()].filter((item) => item.isUsed).length), tone: 'accent' }, { label: 'Nepoužitých', value: String([...usages.values()].filter((item) => !item.isUsed).length), tone: 'muted' }]} compactStats compact={area === 'salon'}>
    {flashMessage(raw('flash')) ? <p role="status" aria-live="polite" className="rounded-[1.25rem] border border-[var(--color-accent)]/30 bg-[rgba(190,160,120,0.1)] px-4 py-3 text-sm text-[var(--color-accent-soft)]">{flashMessage(raw('flash'))}</p> : null}
    <AdminPanel title="Knihovna médií" description="Vyhledávejte soubory, spravujte kolekce a bezpečně nahrazujte assety." compact={area === 'salon'} denseHeader>
      <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center"><form action={base} className="flex min-w-0 flex-1 gap-2"><label className="sr-only" htmlFor="media-search">Hledat média</label><input id="media-search" name="q" defaultValue={search} placeholder="Hledat název, soubor nebo alt text" className="min-h-11 min-w-0 flex-1 rounded-full border border-white/10 bg-black/20 px-4 py-2 text-sm text-white outline-none placeholder:text-white/35 focus:border-[var(--color-accent)]/60"/><button className="min-h-11 shrink-0 rounded-full border border-white/12 px-4 py-2 text-sm text-white transition-colors hover:bg-white/5">Hledat</button></form><a href="#media-upload-form" className="min-h-11 rounded-full bg-[var(--color-accent)] px-5 py-2.5 text-center text-sm font-semibold text-[var(--color-accent-contrast)] transition-opacity hover:opacity-90">Nahrát</a></div>
      <nav aria-label="Filtry médií" className="mb-5 flex flex-col gap-2.5 rounded-[1.15rem] border border-white/8 bg-black/10 p-2.5 sm:flex-row sm:flex-wrap sm:items-center"> <div className="flex flex-wrap gap-2">{([{ value: 'ALL', label: 'Vše' }, { value: 'USED', label: 'Použitá' }, { value: 'UNUSED', label: 'Nepoužitá' }] as const).map((filter) => <Link key={filter.value} href={href({ usage: filter.value === 'ALL' ? undefined : filter.value })} className={`min-h-10 rounded-full border px-3.5 py-2 text-sm transition-colors ${usageFilter === filter.value ? 'border-[var(--color-accent)]/45 bg-[rgba(190,160,120,0.16)] text-white' : 'border-white/10 bg-white/5 text-white/70 hover:bg-white/10'}`}>{filter.label}</Link>)}</div><span className="hidden h-6 border-l border-white/10 sm:block"/><div className="flex flex-wrap gap-2">{collections.map((collection) => <Link key={collection.type} href={href({ collection: category === collection.type ? undefined : collection.type })} className={`min-h-10 rounded-full border px-3.5 py-2 text-sm transition-colors ${category === collection.type ? 'border-[var(--color-accent)]/45 bg-[rgba(190,160,120,0.16)] text-white' : 'border-white/10 bg-white/5 text-white/70 hover:bg-white/10'}`}>{collection.label}</Link>)}</div></nav>
      {category === MediaCollectionType.REFERENCES ? <ReferenceMediaSection area={area} assets={assets} items={referenceItems}/> : null}
      {filtered.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">{filtered.map((asset) => <MediaCard key={asset.id} area={area} asset={asset} usage={usages.get(asset.id)!} memberships={memberships.get(asset.id) ?? []}/>)}</div> : category === MediaCollectionType.REFERENCES ? null : <p className="rounded-[1.35rem] border border-dashed border-white/14 p-6 text-sm text-white/62">Pro tento filtr zatím nejsou žádná média.</p>}
    </AdminPanel><UploadForm area={area}/>
  </AdminPageShell>;
}

function MediaCard({ area, asset, usage, memberships }: { area: AdminArea; asset: Asset; usage: Awaited<ReturnType<typeof getMediaAssetUsage>>; memberships: Membership[] }) { return <MediaAssetDetailDialog area={area} asset={asset} usage={usage} memberships={memberships}/>; }
function UploadForm({ area }: { area: AdminArea }) { return <AdminPanel title="Nahrát médium" description="Nové soubory se ukládají do neutrální struktury images/YYYY/MM/." compact={area === 'salon'} denseHeader><form id="media-upload-form" action={uploadMediaAction} className="space-y-4"><input type="hidden" name="area" value={area}/><MediaUploadDropzone name="file" accept="image/jpeg,image/png,image/webp"/><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-white/55">Titulek<input name="title" maxLength={120} className="mt-1.5 w-full rounded-[.95rem] border border-white/10 bg-black/20 px-3 py-2 text-sm text-white"/></label><label className="text-xs text-white/55">Výchozí alt text<input name="altText" maxLength={160} className="mt-1.5 w-full rounded-[.95rem] border border-white/10 bg-black/20 px-3 py-2 text-sm text-white"/></label></div><button className="rounded-full bg-[var(--color-accent)] px-5 py-2.5 text-sm font-semibold text-[var(--color-accent-contrast)]">Nahrát</button></form></AdminPanel>; }
