import { Section } from "react-email";
import { BookingDetailCard } from "./_components/BookingDetailCard";
import { BookingActionLinks, CalendarNotice } from "./_components/BookingBlocks";
import { ContactBlock, LocationBlock } from "./_components/ContactBlocks";
import { EmailLayout } from "./_components/EmailLayout";

export type BookingRescheduledEmailProps = { brandName: string; serviceName: string; bookingDate: string; bookingTime: string; previousDate: string; previousTime: string; salonName: string; salonAddress: string; salonEmail: string; salonPhone: string; salonPhoneHref: string; salonMapUrl: string; manageReservationUrl?: string; cancellationUrl: string; includeCalendarAttachment: boolean };
export function BookingRescheduledEmail(props: BookingRescheduledEmailProps) { return <EmailLayout brandName={props.brandName} title="Termín rezervace byl změněn" intro="Rezervaci jsme přesunuli na nový čas. Aktuální termín najdete níže." preview={`Rezervace ${props.serviceName} byla přesunuta.`}><BookingDetailCard serviceName={props.serviceName} bookingDate={props.bookingDate} bookingTime={props.bookingTime} extraRows={[{ label: "Původně", value: `${props.previousDate}, ${props.previousTime}` }]} /><Spacer /><LocationBlock name={props.salonName} address={props.salonAddress} mapUrl={props.salonMapUrl} />{props.includeCalendarAttachment ? <><Spacer /><CalendarNotice /></> : null}<BookingActionLinks manageReservationUrl={props.manageReservationUrl} cancellationUrl={props.cancellationUrl} /><Spacer /><ContactBlock email={props.salonEmail} phone={props.salonPhone} phoneHref={props.salonPhoneHref} /></EmailLayout>; }
function Spacer() { return <Section style={{ height: "14px", lineHeight: "14px", fontSize: "14px" }}>&nbsp;</Section>; }
const previewProps: BookingRescheduledEmailProps = { brandName: "PP Studio", serviceName: "Luxusní kosmetické ošetření", bookingDate: "úterý 19. května 2026", bookingTime: "10:00 – 11:30", previousDate: "pondělí 18. května 2026", previousTime: "09:00 – 10:30", salonName: "PP Studio", salonAddress: "Sadová 2, 760 01 Zlín", salonEmail: "info@example.test", salonPhone: "+420 700 000 000", salonPhoneHref: "tel:+420700000000", salonMapUrl: "https://maps.example.test/pp-studio", manageReservationUrl: "https://example.test/rezervace/sprava/preview", cancellationUrl: "https://example.test/rezervace/storno/preview", includeCalendarAttachment: true };
export default Object.assign(BookingRescheduledEmail, { PreviewProps: previewProps });
