ALTER TABLE "Service"
  ADD COLUMN "seoTitle" TEXT,
  ADD COLUMN "idealFor" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "includes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "benefits" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "goodToKnow" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
